/** User-facing Chinese labels for API enum codes. Request payloads stay English. */

const LABELS: Record<string, string> = {
  SUPER_ADMIN: "超级管理员",
  OPERATOR: "运营",
  CUSTOMER_SERVICE: "客服",
  FINANCE: "财务",
  PICKUP_MANAGER: "点位负责人",

  PASSWORD_SETUP_REQUIRED: "待首次改密",
  ACTIVE: "启用",
  SUSPENDED: "已停用",
  INACTIVE: "已停用",
  ENABLED: "已开通",
  DISABLED: "已停用",
  BLOCKED: "已封禁",
  OFF_SHELF: "已下架",

  DRAFT: "草稿",
  SCHEDULED: "已排期",
  OPEN: "开售中",
  CLOSING: "截单中",
  LOCKED: "已锁定",
  FULFILLING: "履约中",
  COMPLETED: "已完成",
  POSTPONED: "已顺延",
  CANCELLED: "已取消",

  PENDING_PAYMENT: "待支付",
  PAID_WAITING_CLOSE: "已支付待截单",
  ALLOCATING: "分配中",
  IN_TRANSIT: "运输中",
  READY_FOR_PICKUP: "待领取",
  PICKED_UP: "已领取",
  CANCELLING: "取消中",
  REFUNDING: "退款中",
  REFUNDED: "已退款",

  SITE_CONFIRMED: "点位已确认",
  VEHICLE_BOOKED: "已约车",
  VEHICLE_DISPATCHED: "车辆已发车",
  ARRIVED: "已到货",
  EXCEPTION: "有异常",

  PENDING_OPERATOR_CONFIRMATION: "待运营确认",
  CONFIRMED: "已确认",

  EXPIRED_PENDING: "已逾期待处理",
  EXTENDED: "已延期",
  REFUND_PENDING: "退款处理中",
  LOSS_RECORDED: "已报损",
  CLOSED: "已关闭",

  CREATED: "已创建",
  SUBMISSION_UNKNOWN: "结果核验中",
  PROCESSING: "处理中",
  RETRYABLE_FAILURE: "可重试失败",
  MANUAL_HOLD: "已挂起",
  SUCCEEDED: "已成功",
  FAILED: "已失败",

  REGISTERED: "已登记",
  REFUND_CONFIRMED: "退款已确认",
  REFUND_PROCESSING: "退款处理中",
  RESOLVED: "已解决",

  SHORT_RECEIPT: "短少",
  QUALITY_REJECTED: "品质拒收",
  PACKAGE_DAMAGED: "包装破损",
  TRANSIT_SHORTAGE: "在途短少",
  TRANSIT_DAMAGE: "在途破损",
  PICKUP_POINT_REJECTED: "点位拒收",
  PICKUP_SHORTAGE: "领取短少",
  PICKUP_DAMAGE: "领取破损",
  QUALITY_CLAIM: "品质投诉",

  CARRIER: "承运方",
  PICKUP_POINT: "自提点",
  PLATFORM: "平台",
  PENDING: "待判定",

  ACCEPTED: "已受理",
  REJECTED: "已拒绝",
  DIRECT_REFUNDING: "直接退款中",
  PENDING_REVIEW: "待审核",
  APPROVED_WAITING_FINANCE: "待财务退款",

  PENDING_DELIVERY: "待投递",
  WECHAT_SENT: "微信已发送",
  IN_APP_AVAILABLE: "站内可见",
  MANUAL_REQUIRED: "需人工处理",
  MANUAL_COMPLETED: "已人工完成",

  PARTIAL_REFUND: "部分退款",
  PICKUP_DEADLINE: "领取截止提醒",
  PICKUP_EXPIRED: "领取已过期",
  CAMPAIGN_POSTPONED: "团期顺延",

  NEW: "待处理",
  CONTACTED: "已联系",

  PAYMENT_SUCCEEDED: "支付成功",
  REFUND_SUCCEEDED: "退款成功",
  PARTIAL_REFUND_SUCCEEDED: "部分退款成功",
  PICKUP_CONFIRMED: "领取确认",

  STAFF_CREATED: "创建员工",
  STAFF_UPDATED: "更新员工",
  STAFF_SUSPENDED: "停用员工",
  STAFF_REACTIVATED: "恢复员工",
  STAFF_ROLE_CHANGED: "变更角色",
  STAFF_PICKUP_SCOPE_CHANGED: "变更点位授权",
  STAFF_CREDENTIAL_RESET: "重置凭据",
  SERVICE_AREA_STATUS_UPDATED: "区域接单状态变更",
  SERVICE_AREA_INTEREST_STATUS_UPDATED: "区域意向状态变更",
  ORDER_NOTIFICATION_MANUAL_COMPLETED: "通知人工完成",
  ORDER_CANCELLED_BY_USER: "用户取消订单",
  PARTIAL_REFUND_EXECUTED: "执行部分退款",
  COMMUNITY_CAMPAIGN_CREATED: "创建团期",
  COMMUNITY_ALLOCATION_DRAFT_CONFIRMED: "确认差异分配",
  COMMUNITY_CANCELLATION_REFUND_SETTLED: "取消退款已结算",
  COMMUNITY_PICKUP_WINDOW_EXTENDED: "领取窗口已延期",
  COMMUNITY_PICKUP_REFUND_REQUESTED: "逾期退款已登记",
  COMMUNITY_PICKUP_LOSS_RECORDED: "逾期报损已登记",
  COMMUNITY_PICKUP_REFUND_SETTLED: "逾期退款已结算",
  COMMUNITY_PICKUP_WINDOW_EXPIRED: "领取窗口已过期",
  COMMUNITY_QUALITY_CASE_REGISTERED: "品质售后已登记",
  COMMUNITY_QUALITY_CASE_ACCEPTED: "品质售后已受理",
  COMMUNITY_QUALITY_CASE_REJECTED: "品质售后已拒绝",
  COMMUNITY_QUALITY_CASE_REFUND_APPROVED: "品质退款已批准",
  COMMUNITY_QUALITY_CASE_FINANCE_EXECUTED: "品质退款已执行",
  COMMUNITY_EVIDENCE_URL_REJECTED: "拒绝外链凭证",
  PICKUP_COMPLETED: "领取完成",
  PICKUP_PARTIAL: "部分领取",

  INTERNAL_STAFF: "内部员工",
  SERVICE_AREA: "服务区域",
  SERVICE_AREA_INTEREST: "区域开通意向",
  ORDER_NOTIFICATION: "订单通知",
  ORDER: "订单",
  CAMPAIGN: "团期",
  FULFILLMENT_EXCEPTION: "履约差异",
  COMMUNITY_PICKUP_RECEIPT: "领取凭据",
  COMMUNITY_CANCELLATION_REQUEST: "取消申请",
  COMMUNITY_PICKUP_WINDOW: "领取窗口",
  COMMUNITY_QUALITY_CASE: "品质售后",
};

export function displayLabel(value: string | null | undefined): string {
  if (!value) return "—";
  return LABELS[value] ?? value;
}

export const STAFF_ROLE_OPTIONS = [
  { value: "SUPER_ADMIN", label: "超级管理员" },
  { value: "OPERATOR", label: "运营" },
  { value: "CUSTOMER_SERVICE", label: "客服" },
  { value: "FINANCE", label: "财务" },
  { value: "PICKUP_MANAGER", label: "点位负责人" },
] as const;
