export const BUSINESS_ERROR_CODES = [
  "AUTH_REQUIRED",
  "UPGRADE_REQUIRED",
  "ACTIVATION_REQUIRED",
  "FORBIDDEN",
  "VALIDATION_ERROR",
  "EVIDENCE_URL_NOT_ALLOWED",
  "RESOURCE_NOT_FOUND",
  "RESOURCE_IN_USE",
  "IDEMPOTENCY_CONFLICT",
  "CAMPAIGN_NOT_OPEN",
  "CAMPAIGN_CLOSED",
  "SKU_STOCK_INSUFFICIENT",
  "OUT_OF_STOCK",
  "SERVICE_AREA_DISABLED",
  "CONCURRENT_MODIFICATION",
  "INVENTORY_INCONSISTENT",
  "EXTERNAL_SERVICE_ERROR",
  "FINANCIAL_INCONSISTENT",
  "INVALID_STATE_TRANSITION",
  "FULFILLMENT_PLAN_MISSING",
  "DELIVERY_SITE_NOT_CONFIRMED",
  "DELIVERY_PLAN_NOT_READY",
  "PICKUP_CODE_UNAVAILABLE",
  "PICKUP_CODE_EXPIRED",
  "PICKUP_CODE_INVALID",
  "FULFILLMENT_EXCEPTION_NOT_READY",
  "REFUND_AMOUNT_EXCEEDED",
  "HTTPS_REQUIRED",
  "PRODUCTION_MOCK_FORBIDDEN",
] as const;

export type BusinessErrorCode = (typeof BUSINESS_ERROR_CODES)[number];

export class BusinessError extends Error {
  public constructor(
    public readonly code: BusinessErrorCode,
    message: string,
    public readonly statusCode = 400,
    public readonly details?: unknown,
  ) {
    super(message);
    this.name = "BusinessError";
  }
}
