const A = '../xiangwei-merchandising-concept-20260915/assets/';
const M = '../../apps/miniprogram/src/assets/';
const products = [
  {id:'corn',name:'本地鲜甜玉米 4根装',desc:'田间采收，香甜饱满；按本期团购统一备货。',cat:'蔬菜',price:12.8,sold:86,img:A+'corn.png'},
  {id:'greens',name:'霜后鲜嫩小青菜 2斤',desc:'鲜嫩清爽，适合家常清炒和煮汤。',cat:'蔬菜',price:9.9,sold:64,img:A+'greens.png'},
  {id:'tofu',name:'乡味手工豆腐干 2袋',desc:'家常味道，开袋即食，也适合搭配热菜。',cat:'豆制品',price:16.8,sold:43,img:M+'product-tofu-strips.jpg'},
  {id:'tomato',name:'本地红番茄 3斤装',desc:'自然熟成，酸甜多汁；具体以实物为准。',cat:'蔬菜',price:13.6,sold:52,img:A+'tomato.png'},
  {id:'potato',name:'现挖小土豆 4斤装',desc:'粉糯耐煮，适合炖菜和香煎。',cat:'蔬菜',price:15.8,sold:37,img:A+'potato.png'},
  {id:'rice',name:'家乡米粉 2袋装',desc:'一碗热乎的家乡味，简单烹煮就能上桌。',cat:'熟食',price:18.8,sold:71,img:M+'product-rice-noodles.jpg'}
];
const categories = [['全部','全'],['蔬菜','🥬'],['水果','🍊'],['粮油','🌾'],['熟食','🍜'],['豆制品','🫘'],['肉蛋','🥚'],['干货','🍄'],['时令','🌿'],['更多','＋']];
const orderStatuses = [['pending','待付款','wallet'],['active','进行中','truck'],['ready','待提货','box'],['done','已提货','check'],['after','退款/售后','return']];
const orders = [
  {status:'active',title:'本期团购 · 鲜甜玉米、豆腐干',detail:'已支付 · 正在统一备货',amount:'¥29.60',img:A+'corn.png'},
  {status:'ready',title:'上期团购 · 霜后小青菜',detail:'待到固定自提点领取',amount:'¥9.90',img:A+'greens.png'},
  {status:'done',title:'往期团购 · 本地红番茄',detail:'已提货',amount:'¥13.60',img:A+'tomato.png'}
];
const state = {page:'home',cat:'全部',search:'',cart:{},sheet:null,pickup:'石亭国庆超市',noticeOn:false};
const app = document.getElementById('app');
const esc = x => String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = x => '¥'+x.toFixed(2);
const count = () => Object.values(state.cart).reduce((a,b)=>a+b,0);
const total = () => products.reduce((a,p)=>a+p.price*(state.cart[p.id]||0),0);
function icon(name){const p={home:'<path d="m3 11 9-8 9 8v9a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1z"/>',cart:'<circle cx="9" cy="20" r="1"/><circle cx="18" cy="20" r="1"/><path d="M2 3h2l2.4 12h12.8l2-9H5"/>',user:'<circle cx="12" cy="8" r="4"/><path d="M4 21c0-4 3.3-7 8-7s8 3 8 7"/>',search:'<circle cx="10.7" cy="10.7" r="7"/><path d="m16 16 5 5"/>',wallet:'<rect x="3" y="5" width="18" height="15" rx="3"/><path d="M16 12h5M3 8h15"/>',truck:'<path d="M2 6h12v11H2zM14 10h4l4 4v3h-8"/><circle cx="6" cy="18" r="2"/><circle cx="18" cy="18" r="2"/>',box:'<path d="m3 7 9-4 9 4v12l-9 3-9-3zM3 7l9 4 9-4M12 11v11"/>',check:'<rect x="4" y="3" width="16" height="18" rx="3"/><path d="m8 12 3 3 5-6"/>',return:'<path d="M20 11a8 8 0 1 1-3-6"/><path d="M20 3v6h-6M9 11h6M12 8v6"/>'};return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${p[name]}</svg>`}
function navHead(title='乡味集'){return `<div class="status"><span>9:41</span><span class="status-icons">▥ ▰ ●</span></div><div class="wechat-nav">${esc(title)}<span class="capsule" aria-hidden="true"><span>•••</span><span>◎</span></span></div>`}
function tabs(){return `<nav class="tabbar" aria-label="底部导航">${[['home','首页','home'],['cart','购物车','cart'],['profile','我的','user']].map(([page,label,ico])=>`<button type="button" data-page="${page}" class="${state.page===page?'active':''}" aria-current="${state.page===page?'page':'false'}">${icon(ico)}<span>${label}</span>${page==='cart'&&count()?`<span class="cart-dot">${count()}</span>`:''}</button>`).join('')}</nav>`}
function visible(){const q=state.search.trim().toLocaleLowerCase(),cat=state.cat==='更多'?'全部':state.cat;return products.filter(p=>(cat==='全部'||p.cat===cat)&&(!q||`${p.name} ${p.desc}`.toLocaleLowerCase().includes(q)))}
function productList(){const items=visible();if(!items.length)return '<div class="empty">这个分类暂时没有本期商品<br>可以看看其他好味道</div>';return items.map(p=>`<article class="product-card" data-product="${p.id}" tabindex="0" role="button" aria-label="查看${esc(p.name)}"><div class="photo-strip"><span class="photo-cell"><img src="${p.img}" alt="${esc(p.name)}"></span><span class="photo-cell"><img src="${p.img}" alt="商品细节示意"></span><span class="photo-cell"><img src="${p.img}" alt="商品局部示意"></span></div><h3 class="product-name">${esc(p.name)}</h3><p class="product-desc">${esc(p.desc)}</p><span class="sold">已售 ${p.sold} 件</span><div class="price-row"><div class="price"><small>¥</small>${p.price.toFixed(2)}</div><button type="button" class="buy" data-buy="${p.id}">加入购物车</button></div><div class="date-row"><span>截单：9月30日 20:00</span><span>预计到货：10月2日起</span></div></article>`).join('')}
function home(){return `<div class="scroll" id="main-scroll"><header class="home-hero">${navHead()}<div class="hero-inner"><button class="pickup-line" data-action="pickup"><span><span class="loc-main">${esc(state.pickup)} ›</span><span class="loc-sub">河北省保定市涞水县石亭镇 · 当前固定自提点</span></span><img src="${A}pickup-point.png" alt="自提点示例照片"></button></div></header><div class="home-body"><section class="feature-card" aria-label="本期团购"><div class="feature-cover"><img src="${A}hero-field.png" alt="田间蔬菜"><div class="feature-copy"><span class="label">乡味集 · 本期团购</span><strong>新鲜上桌<br>好味正当时</strong><small>附近自提 · 按团集中到货</small></div></div><div class="feature-bottom"><div><b>距本期截单还有 6 天</b><small>示例团期 · 9月30日 20:00 截单</small></div><button class="soft-action" data-action="notice">截单提醒</button></div></section><section class="category-grid" aria-label="商品分类">${categories.map(([label,visual])=>`<button type="button" class="category-tile ${state.cat===label?'active':''}" data-category="${label}"><span class="category-visual">${visual}</span><span>${label}</span></button>`).join('')}</section><div class="ribbon"><div><b>－ 正 在 团 购 －</b><small>乡土好物 · 按团集中到货</small></div></div><div class="search-zone"><label class="search-box">${icon('search')}<input id="search" type="search" placeholder="搜索本期商品" value="${esc(state.search)}" autocomplete="off" aria-label="搜索本期商品"></label></div><div class="filter-row" aria-label="商品筛选">${['全部','蔬菜','豆制品','熟食','水果','粮油','肉蛋'].map(label=>`<button type="button" data-category="${label}" class="${state.cat===label?'active':''}">${label}</button>`).join('')}</div><div class="product-area" id="product-area">${productList()}</div></div></div>`}
function profile(){return `<div class="scroll" id="main-scroll"><header class="profile-hero">${navHead('个人中心')}<div class="profile-identity"><img src="${M}avatar-persimmon.png" alt="示例头像"><div><b>乡味集用户</b><small>固定自提点：${esc(state.pickup)}</small></div></div></header><div class="profile-body"><section class="panel"><div class="panel-heading"><span>我的订单</span><button class="minor text-button" data-orders="all">查看全部订单 ›</button></div><div class="order-steps">${orderStatuses.map(([key,label,ico])=>`<button type="button" data-orders="${key}">${icon(ico)}<span>${label}</span></button>`).join('')}</div></section><section class="panel pickup-panel"><button class="panel-heading panel-button" data-action="pickup"><span>我的当前自提点</span><span class="minor">查看 / 切换 ›</span></button><button class="pickup-info panel-button" data-action="pickup"><img src="${A}pickup-point.png" alt="自提点示例照片"><span><b>${esc(state.pickup)}</b><p>河北省保定市涞水县石亭镇石亭村</p><small>到点出示取货码领取</small></span></button></section><section class="panel menu-panel">${[['🔔','消息提醒','notice'],['▣','取货码','code'],['◎','个人资料','account'],['☏','帮助与客服','help'],['◈','隐私与协议','privacy'],['↪','退出登录','logout']].map(([ico,label,action])=>`<button type="button" class="menu-row ${action==='logout'?'logout':''}" data-action="${action}"><span class="menu-icon">${ico}</span><span>${label}</span><span class="chev">›</span></button>`).join('')}</section></div></div>`}
function cart(){const items=products.filter(p=>state.cart[p.id]);return `<div class="scroll cart-page" id="main-scroll"><header class="plain-head">${navHead('购物车')}<h2>我的购物车</h2></header><div class="cart-content"><div class="cart-point"><b>固定自提点 · ${esc(state.pickup)}</b>本期商品在同一自提点统一领取</div>${items.length?items.map(p=>`<div class="cart-item"><img src="${p.img}" alt=""><div class="cart-item-content"><b>${esc(p.name)}</b><p>${money(p.price)}</p><div class="qty"><button type="button" data-qty="${p.id}" data-delta="-1" aria-label="减少${esc(p.name)}">−</button><span>${state.cart[p.id]}</span><button type="button" data-qty="${p.id}" data-delta="1" aria-label="增加${esc(p.name)}">＋</button></div></div></div>`).join(''):'<div class="empty">购物车还是空的<br>去首页挑选本期好味道吧</div>'}${items.length?`<div class="cart-summary"><span>共 ${count()} 件商品</span><b>${money(total())}</b></div><p class="cart-hint">原型仅演示购物车样式，不提交订单或支付。</p><button type="button" class="primary-wide" data-action="checkout">去结算 · 原型示意</button>`:'<button type="button" class="primary-wide" data-page="home">去逛逛</button>'}</div></div>`}
function overlay(title,body){return `<div class="overlay" data-overlay="true"><section class="sheet" role="dialog" aria-modal="true" aria-label="${esc(title)}"><div class="sheet-head"><b>${esc(title)}</b><button type="button" data-action="close" aria-label="关闭">×</button></div>${body}</section></div>`}
function sheet(){const s=state.sheet;if(!s)return '';if(s.type==='product'){const p=products.find(x=>x.id===s.id);return overlay('本期商品',`<img class="sheet-image" src="${p.img}" alt="${esc(p.name)}"><h3>${esc(p.name)}</h3><p>${esc(p.desc)}</p><div class="sheet-price">${money(p.price)}</div><div class="notice">本期 9月30日 20:00 截单，预计 10月2日起到固定自提点。具体领取时间以订单进度为准。</div><div class="pickup-actions"><button type="button" data-action="navigate">⌖ 导航到自提点</button><button type="button" data-action="call-point">☎ 联系自提点</button></div><button type="button" class="primary-wide" data-buy="${p.id}">加入购物车</button>`)}if(s.type==='orders'){const label=s.filter==='all'?'全部订单':orderStatuses.find(x=>x[0]===s.filter)?.[1]||'订单';const list=orders.filter(o=>s.filter==='all'||o.status===s.filter);return overlay(label,`<p>状态示例仅用于查看版式；正式页面继续使用真实订单状态。</p>${list.length?list.map(o=>`<div class="sheet-row"><img src="${o.img}" alt=""><div><b>${esc(o.title)}</b><small>${esc(o.detail)} · ${o.amount}</small></div></div>`).join(''):'<div class="empty">此状态下暂无示例订单</div>'}`)}if(s.type==='pickup')return overlay('当前自提点',`<img class="sheet-image" src="${A}pickup-point.png" alt="自提点示例照片"><h3>选择固定自提点</h3><p>示例点位供评审交互使用。实际可选范围由后端已开放点位决定。</p><div class="chip-list">${['石亭国庆超市','涞水便民自提点'].map(name=>`<button class="chip ${state.pickup===name?'active':''}" data-pickup="${name}">${name}</button>`).join('')}</div><div class="pickup-actions"><button type="button" data-action="navigate">⌖ 导航到自提点</button><button type="button" data-action="call-point">☎ 联系自提点</button></div>`);if(s.type==='notice')return overlay('消息提醒',`<div class="notice">沿用现有的消息提醒入口和订阅规则。这里仅演示新布局中的入口位置，不发起微信授权。</div><button type="button" class="primary-wide" data-action="toggle-notice">${state.noticeOn?'已标记关注 · 点击取消演示':'关注本期截单提醒 · 原型演示'}</button>`);const copy={code:['取货码','正式页面会按已有订单展示真实取货码。'],account:['个人资料','正式页面沿用已有的姓名、手机号与资料编辑流程。'],help:['帮助与客服','正式页面沿用现有客服入口与下单领取说明。'],privacy:['隐私与协议','正式页面沿用现有用户协议和隐私说明。'],logout:['退出登录','原型不会改变实际登录状态。正式页面沿用当前退出流程。'],checkout:['结算预览','本次只评审布局，原型不提交订单或支付。'],navigate:['导航到自提点','正式小程序在自提点配置了坐标时打开微信地图；未配置坐标会提示。原型不启动地图。'],"call-point":['联系自提点','正式小程序在自提点配置了联系电话时调起拨号；未配置电话会提示。原型不拨号。']}[s.type]||['提示','该入口仅展示布局。'];return overlay(copy[0],`<div class="notice">${copy[1]}</div>`)}
function render(keep=false){const y=keep?app.querySelector('#main-scroll')?.scrollTop||0:0;app.innerHTML=(state.page==='home'?home():state.page==='profile'?profile():cart())+tabs()+sheet();if(keep)app.querySelector('#main-scroll').scrollTop=y}
function renderSheet(){app.querySelector('.overlay')?.remove();app.insertAdjacentHTML('beforeend',sheet())}
app.addEventListener('click',e=>{const t=e.target;let el=t.closest('[data-page]');if(el){state.page=el.dataset.page;state.sheet=null;render();return}el=t.closest('[data-buy]');if(el){state.cart[el.dataset.buy]=(state.cart[el.dataset.buy]||0)+1;state.sheet=null;render(true);return}el=t.closest('[data-qty]');if(el){const id=el.dataset.qty;state.cart[id]=Math.max(0,(state.cart[id]||0)+Number(el.dataset.delta));render(true);return}el=t.closest('[data-category]');if(el){state.cat=el.dataset.category;render(true);return}el=t.closest('[data-pickup]');if(el){state.pickup=el.dataset.pickup;state.sheet=null;render(true);return}el=t.closest('[data-orders]');if(el){state.sheet={type:'orders',filter:el.dataset.orders};renderSheet();return}el=t.closest('[data-action]');if(el){const action=el.dataset.action;if(action==='close'){state.sheet=null;renderSheet();return}if(action==='toggle-notice'){state.noticeOn=!state.noticeOn;renderSheet();return}state.sheet={type:action};renderSheet();return}el=t.closest('[data-product]');if(el){state.sheet={type:'product',id:el.dataset.product};renderSheet();return}if(t.dataset.overlay){state.sheet=null;renderSheet()}});
app.addEventListener('input',e=>{if(e.target.id==='search'){state.search=e.target.value;app.querySelector('#product-area').innerHTML=productList()}});
app.addEventListener('keydown',e=>{if(e.key==='Escape'&&state.sheet){state.sheet=null;renderSheet()}if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-product]')){e.preventDefault();state.sheet={type:'product',id:e.target.dataset.product};renderSheet()}});
render();
