import {test,expect} from "@playwright/test";
const base=process.env.E2E_API_BASE_URL??"http://127.0.0.1:3101";
const headers={"x-demo-user-id":"rbac-admin","x-demo-role":"SUPER_ADMIN"};
test("自定义角色配置、员工分配、只读菜单与撤权形成闭环",async({page,request,browser},testInfo)=>{
  const suffix=`${Date.now()}${Math.floor(Math.random()*10000)}`;
  const create=await request.post(`${base}/api/v1/admin/staff`,{headers,data:{displayName:"权限配置管理员",username:`rbac.admin.${suffix}`,phone:`136${suffix.slice(-8)}`,role:"SUPER_ADMIN",pickupPointIds:[]}});
  expect(create.status()).toBe(201);const root=(await create.json()).data;
  await page.goto("/");await page.getByLabel("账号").fill(`rbac.admin.${suffix}`);await page.getByLabel("密码").fill(root.temporaryPassword);await page.getByRole("button",{name:/登\s*录/}).click();
  await page.getByLabel("新密码",{exact:true}).fill("RBAC-admin-Password123!");await page.getByLabel("确认新密码").fill("RBAC-admin-Password123!");await page.getByRole("button",{name:"保存新密码"}).click();
  await expect(page.getByRole("heading",{name:"运营工作台"})).toBeVisible();
  await page.getByRole("menuitem",{name:"角色管理",exact:true}).click();
  const operatorRow=page.getByRole("row").filter({has:page.getByText("运营",{exact:true})});
  await operatorRow.getByRole("button",{name:/^更\s*多$/}).click();
  await expect(page.getByRole("menuitem",{name:"删除角色",exact:true})).toBeVisible();
  await page.keyboard.press("Escape");
  await page.getByRole("button",{name:"新增角色",exact:true}).click();
  const modal=page.getByRole("dialog",{name:"新增角色"});await modal.getByLabel("角色名称").fill(`只读商品${suffix}`);await modal.getByRole("checkbox",{name:"查看商品列表",exact:true}).check();await modal.getByRole("button",{name:/^保\s*存$/}).click();await expect(modal).not.toBeVisible();
  const row=page.getByRole("row").filter({hasText:`只读商品${suffix}`});await expect(row).toBeVisible();
  await page.screenshot({path:testInfo.outputPath("roles.png"),fullPage:true});
  await page.getByRole("button",{name:"新增角色",exact:true}).click();
  const disposableName=`待删角色${suffix}`;const disposableDialog=page.getByRole("dialog",{name:"新增角色"});
  await disposableDialog.getByLabel("角色名称").fill(disposableName);await disposableDialog.getByRole("button",{name:/^保\s*存$/}).click();
  const disposableRow=page.getByRole("row").filter({hasText:disposableName});await expect(disposableRow).toBeVisible();
  await disposableRow.getByRole("button",{name:/^更\s*多$/}).click();await page.getByRole("menuitem",{name:"删除角色",exact:true}).click();
  const deleteDialog=page.getByRole("dialog",{name:`删除角色“${disposableName}”？`});
  await deleteDialog.getByRole("button",{name:/^删\s*除$/}).click();await expect(disposableRow).toHaveCount(0);
  await page.getByRole("menuitem",{name:"员工管理",exact:true}).click();await page.getByRole("button",{name:"新增员工",exact:true}).click();
  const staffModal=page.getByRole("dialog",{name:"新增内部员工"});await staffModal.getByLabel("姓名",{exact:true}).fill(`只读员工${suffix}`);await staffModal.getByLabel("登录账号").fill(`rbac.viewer.${suffix}`);await staffModal.getByLabel("手机号").fill(`137${suffix.slice(-8)}`);await staffModal.getByLabel("角色",{exact:true}).click();await staffModal.getByText(`只读商品${suffix}`,{exact:true}).click();
  const created=page.waitForResponse(r=>r.url().endsWith("/api/v1/admin/staff")&&r.request().method()==="POST");await staffModal.getByRole("button",{name:"创建账号"}).click();const response=await created;expect(response.status()).toBe(201);const employee=(await response.json()).data;
  const context=await browser.newContext();const viewer=await context.newPage();await viewer.goto(page.url());await viewer.getByLabel("账号").fill(`rbac.viewer.${suffix}`);await viewer.getByLabel("密码").fill(employee.temporaryPassword);await viewer.getByRole("button",{name:/登\s*录/}).click();await viewer.getByLabel("新密码",{exact:true}).fill("RBAC-viewer-Password123!");await viewer.getByLabel("确认新密码").fill("RBAC-viewer-Password123!");await viewer.getByRole("button",{name:"保存新密码"}).click();
  await expect(viewer.getByRole("heading",{name:"商品列表",exact:true})).toBeVisible();await expect(viewer.getByRole("button",{name:"新增商品",exact:true})).toHaveCount(0);await expect(viewer.getByRole("menuitem",{name:"财务",exact:true})).toHaveCount(0);await expect(viewer.getByRole("menuitem",{name:"角色管理",exact:true})).toHaveCount(0);
  await viewer.screenshot({path:testInfo.outputPath("readonly.png"),fullPage:true});
  const credentialDialog=page.getByRole("dialog",{name:"临时密码（仅显示一次）"});
  await expect(credentialDialog).toBeVisible();
  await credentialDialog.getByRole("button",{name:/^我\s*已\s*安\s*全\s*交\s*付\s*给\s*员\s*工$/}).click();
  await expect(credentialDialog).not.toBeVisible();
  await page.getByRole("menuitem",{name:"角色管理",exact:true}).click();
  await row.getByRole("button",{name:/^更\s*多$/}).click();
  await expect(page.getByRole("menuitem",{name:"删除角色",exact:true})).toHaveAttribute("aria-disabled","true");
  await page.keyboard.press("Escape");
  const policies=await request.get(`${base}/api/v1/admin/access/roles`,{headers});const role=(await policies.json()).data.find((r:{name:string})=>r.name===`只读商品${suffix}`);
  const revoked=await request.patch(`${base}/api/v1/admin/access/roles/${role.id}`,{headers,data:{...role,permissions:[]}});expect(revoked.status()).toBe(200);await viewer.reload();await expect(viewer.getByLabel("账号")).toBeVisible();await context.close();
});
