import { expect, test } from '@playwright/test';

const apiBase = process.env.E2E_API_BASE_URL ?? 'http://127.0.0.1:3101';
const headers = { 'x-demo-user-id': 'demo-super-admin', 'x-demo-role': 'SUPER_ADMIN' };
test('商品主图真实上传、公开读取、编辑保留与移除', async ({ page, request }, testInfo) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  const suffix = String(Date.now());
  const staffResponse = await request.post(`${apiBase}/api/v1/admin/staff`, { headers, data: { displayName: '主图测试运营', username: `image.${suffix}`, phone: `137${suffix.slice(-8)}`, role: 'SUPER_ADMIN', pickupPointIds: [] } });
  expect(staffResponse.ok()).toBeTruthy();
  const staff = (await staffResponse.json()).data;
  const categoryName = `图片测试分类${suffix}`;
  const categoryResponse = await request.post(`${apiBase}/api/v1/admin/catalog/categories`, { headers, data: { name: categoryName } });
  expect(categoryResponse.ok()).toBeTruthy();
  await page.goto('/');
  await page.getByLabel('账号').fill(`image.${suffix}`);
  await page.getByLabel('密码').fill(staff.temporaryPassword);
  await page.getByRole('button', { name: /登\s*录/ }).click();
  await page.getByLabel('新密码', { exact: true }).fill('image upload password');
  await page.getByLabel('确认新密码').fill('image upload password');
  await page.getByRole('button', { name: '保存新密码' }).click();
  await page.getByText('商品管理', { exact: true }).click();
  await page.getByRole('button', { name: '新增商品' }).click();
  const dialog = page.getByRole('dialog');
  const title = `主图商品${suffix}`;
  await page.getByLabel('商品名称').fill(title);
  await page.getByLabel('分类', { exact: true }).click();
  await page.getByText(categoryName, { exact: true }).click();
  await page.getByLabel('产地').fill('本地');
  await page.getByLabel('销售规格（包装单位）').fill('一份');
  await page.getByLabel('售价（元）').fill('12.50');
  await page.getByLabel('默认团期可售量').fill('10');
  let releaseUpload!: () => void;
  const release = new Promise<void>(resolve => { releaseUpload = resolve; });
  await page.route('**/api/v1/admin/product-images', async route => {
    const response = await route.fetch();
    await release;
    await route.fulfill({ response });
  });
  const uploaded = page.waitForResponse(response => response.url().endsWith('/api/v1/admin/product-images') && response.request().method() === 'POST');
  await page.getByLabel('上传商品主图').setInputFiles({ name: 'sample.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAIAAAD91JpzAAAAEElEQVR4nGP4EGQERAwQCgArtgXRlFwMYgAAAABJRU5ErkJggg==', 'base64') });
  await expect(page.getByRole('button', { name: '保存商品' })).toBeDisabled();
  releaseUpload();
  const uploadResponse = await uploaded;
  expect(uploadResponse.ok(), await uploadResponse.text()).toBeTruthy();
  const imageUrl = (await uploadResponse.json()).data.imageUrl;
  await expect(dialog.getByRole('img', { name: '商品主图', exact: true })).toHaveAttribute('src', imageUrl);
  const publicImage = await request.get(`${apiBase}${imageUrl}`);
  expect(publicImage.ok()).toBeTruthy();
  expect(publicImage.headers()['content-type']).toContain('image/webp');
  await page.getByRole('button', { name: '保存商品' }).click();
  await expect(dialog).not.toBeVisible();
  const row = page.getByRole('row').filter({ hasText: title });
  await expect(row.getByRole('img', { name: '商品主图', exact: true })).toHaveAttribute('src', imageUrl);
  await row.getByRole('button', { name: /编\s*辑/ }).click();
  await expect(dialog.getByRole('img', { name: '商品主图', exact: true })).toHaveAttribute('src', imageUrl);
  await page.getByLabel('上传商品主图').setInputFiles({ name: 'invalid.svg', mimeType: 'image/svg+xml', buffer: Buffer.from('<svg/>') });
  await expect(dialog.getByText(/请选择 JPG、PNG 或 WebP 图片/)).toBeVisible();
  await expect(dialog.getByRole('img', { name: '商品主图', exact: true })).toHaveAttribute('src', imageUrl);
  await page.setViewportSize({ width: 1440, height: 1200 });
  await expect(page.locator('.ant-message-notice')).toHaveCount(0);
  const screenshot = testInfo.outputPath('product-image-edit.png');
  await dialog.screenshot({ path: screenshot });
  await testInfo.attach('商品主图编辑与失败保留', { path: screenshot, contentType: 'image/png' });
  await page.setViewportSize({ width: 1440, height: 720 });
  await page.getByRole('button', { name: '保存商品' }).scrollIntoViewIfNeeded();
  await expect(page.getByRole('button', { name: '保存商品' })).toBeInViewport();
  await page.getByLabel('产地').fill('本地农场');
  await page.getByRole('button', { name: '保存商品' }).click();
  await expect(dialog).not.toBeVisible();
  await expect(row.getByRole('img', { name: '商品主图', exact: true })).toHaveAttribute('src', imageUrl);
  await row.getByRole('button', { name: /编\s*辑/ }).click();
  await page.getByRole('button', { name: '移除主图' }).click();
  await page.getByRole('button', { name: '保存商品' }).click();
  await expect(dialog).not.toBeVisible();
  await expect(row.getByText('暂无图片')).toBeVisible();
});
