const A='../xiangwei-merchandising-concept-20260915/assets/';
const initial={title:'鲜甜黄玉米',intro:'颗粒饱满，清甜多汁。蒸煮后软糯香甜，早餐、轻食都合适。\n收到后请冷藏保存，尽早食用。',price:'12.90',unit:'2根/份',images:[A+'corn.png'],details:['detail-example.svg'],name:'定兴三中自提点',address:'河北省保定市定兴县定兴镇河北定兴第三中学旁',hours:'每日 09:00—20:00',contact:'栗子',photo:A+'pickup-point.png'};
let s=structuredClone(initial), saved=structuredClone(initial), admin='product', page='detail', list=false, pointEdit=false, pointDraft=null, index=0, cart=0, uploadTarget='', statuses=Array(5).fill('none'), enabled=true, logged=true;
const names=['到货取货提醒','发货提醒','订单状态提醒','退款成功提醒','领取到期提醒'];
const descriptions=['商品到点后及时领取','了解商品配送进度','接收团期、地点等重要变更','退款结果及时知晓','到期前提醒，避免忘记领取'];
const $=q=>document.querySelector(q), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const img=(src,alt,cls='')=>src?`<img src="${esc(src)}" alt="${esc(alt)}" class="${cls}">`:`<div class="image-placeholder ${cls}">暂无图片</div>`;
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),2800)}
function modal(title,body,actions='',wide=false){$('#overlay').innerHTML=`<div class="dialog ${wide?'wide':''}" role="dialog" aria-modal="true" aria-label="${esc(title)}"><div class="dialog-head"><h2>${title}</h2><button data-act="close" aria-label="关闭">×</button></div>${body}<div class="dialog-actions">${actions||'<button data-act="close">知道了</button>'}</div></div>`;$('#overlay').hidden=false;$('#overlay button')?.focus()}
function close(){$('#overlay').hidden=true;$('#overlay').innerHTML=''}
function field(label,key,value,extra=''){return `<label class="field"><span>${label}</span><input data-field="${key}" value="${esc(value)}" ${extra}></label>`}
function pointCard(){return `<div class="mini-point" data-page="pickup" role="button" tabindex="0">${s.photo?img(s.photo,'自提点实景'):'<span class="point-placeholder">⌖</span>'}<div class="grow"><b>${esc(s.name)}</b><small>${esc(s.address)}</small></div><span class="arrow">›</span></div>`}
function renderAdmin(){document.querySelectorAll('[data-admin]').forEach(e=>e.classList.toggle('active',e.dataset.admin===admin));
if(admin==='point'){renderPoint();return}
if(list){$('#admin').innerHTML=`<div class="breadcrumb">商品与团期 / 商品管理</div><div class="pagehead"><div><h1>商品管理</h1><p>图片、介绍和销量，一处看清楚</p></div></div><div class="panel"><table><thead><tr><th>商品</th><th>累计净销量</th><th>操作</th></tr></thead><tbody><tr><td>${img(s.images[0],'封面','tiny-photo')} ${esc(s.title)}</td><td>128 件</td><td><button data-act="edit-product">编辑</button> <button data-page="detail">预览</button></td></tr></tbody></table></div><p class="hint">销量由订单自动统计，不能手动修改；不计未付款、已取消订单。</p>`;return}
$('#admin').innerHTML=`<div class="breadcrumb"><button data-act="product-list">商品管理</button> / 编辑商品</div><div class="pagehead"><div><h1>把商品介绍清楚</h1><p>先看图，再看介绍；右侧同步预览小程序效果。</p></div><button data-page="detail">预览商品</button></div>
<div class="panel"><div class="panelhead"><span class="number">01</span><h2>基本信息</h2></div>${field('商品名称 <em>*</em>','title',s.title,'maxlength="40"')}<label class="field"><span>商品介绍 <em>*</em><small>说清特点、口感、用途和保存建议</small></span><textarea data-field="intro" rows="4" maxlength="300">${esc(s.intro)}</textarea><span class="count"><b id="intro-count">${s.intro.length}</b> / 300</span></label><p class="hint">小程序商品详情完整展示，列表显示摘要。销售计价单位收进下方“其他设置”。</p></div>
<div class="panel"><div class="panelhead"><span class="number">02</span><h2>商品图片</h2><span class="muted">${s.images.length} / 5 张</span></div><p class="hint">第一张为封面；详情页可左右滑动。建议正方形，每张不超过 5 MB。</p><div class="gallery-editor">${s.images.map((src,i)=>`<div class="thumb">${img(src,'商品图片'+(i+1))}${i===0?'<span class="coverbadge">封面</span>':''}<div class="thumb-actions"><button data-act="left-image" data-i="${i}" ${i===0?'disabled':''} title="向前移">←</button><button data-act="right-image" data-i="${i}" ${i===s.images.length-1?'disabled':''} title="向后移">→</button><button data-act="remove-image" data-i="${i}" aria-label="删除第${i+1}张图片">×</button></div></div>`).join('')}${s.images.length<5?'<button class="upload" data-act="upload-gallery"><b>＋</b>上传图片<small>可一次选多张</small></button>':''}</div><div class="inlinebar"><span class="hint">拖动顺序的演示用左右箭头操作，向前移到首张即设为封面。</span><button data-act="sample-gallery" ${s.images.length>=5?'disabled':''}>添加示例图</button></div></div>
<div class="panel"><div class="panelhead"><span class="number">03</span><h2>商品详情长图</h2><span class="muted">${s.details.length} / 10 张</span></div><p class="hint">用于图文介绍、食用方法、售后说明。按顺序放在商品页底部，等比展示、不裁切；每张不超过 10 MB。</p><div class="detail-assets">${s.details.map((src,i)=>`<div class="assetrow">${img(src,'详情长图'+(i+1))}<div class="grow"><b>详情长图 ${i+1}</b><small>原图比例 · 连续展示</small></div><button data-act="view-detail" data-i="${i}">查看</button><button data-act="left-detail" data-i="${i}" ${i===0?'disabled':''}>上移</button><button data-act="remove-detail" data-i="${i}" aria-label="删除详情图">×</button></div>`).join('')||'<div class="empty">还没有详情图，不上传时小程序隐藏此区域</div>'}</div><div class="inlinebar"><button data-act="upload-detail" ${s.details.length>=10?'disabled':''}>＋ 上传长图</button><button data-act="sample-detail" ${s.details.length>=10?'disabled':''}>添加示例长图</button></div></div>
<div class="panel"><div class="panelhead"><span class="number">04</span><h2>商品销量</h2><span class="pill">自动统计</span></div><div class="sales"><div class="metric"><b>136</b><small>累计支付件数</small></div><div class="metric"><b>8</b><small>成功退款件数</small></div><div class="metric"><b>128</b><small>累计净销量 · 小程序展示</small></div></div><p class="hint">以购买数量统计，跨团期累计；1 份 = 1 件，不按订单笔数。以上均为示例数据。</p></div>
<div class="panel"><details><summary>其他设置 <small>计价单位、售价</small></summary><div class="row">${field('计价单位','unit',s.unit,'maxlength="30"')}${field('默认售价（元）','price',s.price,'type="number" min="0.01" step="0.01"')}</div><p class="hint">保留“2根/份”等交易信息，供下单及提货核对；商品介绍不覆盖历史订单规格。</p></details></div><div class="savebar"><span>当前内容为演示草稿</span><button data-act="cancel-product">取消</button><button class="primary" data-act="save-product">保存商品</button></div>`}
function renderPoint(){if(!pointEdit){$('#admin').innerHTML=`<div class="breadcrumb">自提点与区域 / 自提点管理</div><div class="pagehead"><div><h1>自提点管理</h1><p>实景照片帮助用户找到正确的领取地点</p></div><button class="primary" data-act="new-point">新增自提点</button></div><div class="panel"><table><thead><tr><th>自提点</th><th>负责人</th><th>操作</th></tr></thead><tbody><tr><td>${img(s.photo,'自提点实景','tiny-photo')}<b>${esc(s.name)}</b><p class="hint">${esc(s.address)}</p></td><td>${esc(s.contact)}</td><td><button data-act="edit-point">编辑</button> <button data-page="pickup">预览</button></td></tr></tbody></table></div><div class="softnote">新增自提点必须上传一张实景照片；已有点位缺照片时显示地点图标，不使用来源不明的店铺图片。</div>`;return}
const p=pointDraft;$('#admin').innerHTML=`<div class="breadcrumb"><button data-act="cancel-point">自提点管理</button> / ${p.isNew?'新增':'编辑'}自提点</div><div class="pagehead"><div><h1>${p.isNew?'新增':'编辑'}自提点</h1><p>独立表单页面，填写完成后保存返回列表。</p></div></div><div class="panel"><h2>点位实景</h2><label class="field"><span>自提点照片 <em>*</em></span></label><div class="point-photo">${p.photo?img(p.photo,'自提点照片'):'<div class="empty">上传门头或容易辨认的实景照片</div>'}</div><div class="inlinebar"><button data-act="upload-point">${p.photo?'更换照片':'上传照片'}</button><button data-act="sample-point">使用示例照片</button>${p.photo?'<button data-act="remove-point-photo">移除</button>':''}</div><p class="hint">仅一张，JPG / PNG / WebP，最大 5 MB。图片会用于首页、商品详情、我的及自提点详情。</p></div><div class="panel"><h2>基本信息</h2>${field('自提点名称 <em>*</em>','point.name',p.name,'maxlength="40"')}${field('详细地址 <em>*</em>','point.address',p.address,'maxlength="120"')}${field('营业时间','point.hours',p.hours,'maxlength="40"')}${field('点位负责人','point.contact',p.contact,'readonly')}<p class="hint">负责人沿用员工授权关系；此原型不改变一位点位负责人规则。</p></div><div class="savebar"><button data-act="cancel-point">取消</button><button class="primary" data-act="save-point">保存自提点</button></div>`}
function subBanner(){const n=statuses.filter(x=>x==='accepted').length;if(enabled&&n===5)return '<div class="sub-ok" data-page="messages">✓ 本次消息已订阅 <span>去「我的 · 消息提醒」管理 ›</span></div>';const title=!logged?'订阅消息，不错过提货':!enabled?'消息提醒已关闭':n?`已订阅 ${n} 类，还有提醒未开启`:statuses.includes('used')?'本次提醒已用完，可再次订阅':'到货通知，别错过';return `<div class="subscription-card"><span class="notice-icon">♧</span><div class="grow"><b>${title}</b><small>在「我的 · 消息提醒」查看或关闭</small></div><button data-act="subscribe">${!enabled?'开启提醒':n?'继续订阅':'订阅消息'}</button></div>`}
function renderMini(){document.querySelectorAll('[data-page]').forEach(e=>e.classList.toggle('active',e.dataset.page===page));$('#mini-title').textContent=({home:'乡味集',detail:'商品详情',profile:'我的',messages:'消息提醒',pickup:'自提点详情'})[page];let html='';
if(page==='home')html=`<div class="home-point"><small>当前自提点</small>${pointCard()}</div>${subBanner()}<div class="banner">${img(A+'hero-field.png','田野风景')}<div>当季新鲜好物<br><b>一起带回家</b></div></div><div class="mini-heading"><b>本期团购</b><small>按团集中到货 · 到点领取</small></div><section class="product-list"><div data-page="detail">${img(s.images[0],'商品封面')}</div><div class="info"><h3 data-page="detail">${esc(s.title)}</h3><p>${esc(s.intro)}</p><div class="price-row"><span class="price">¥${esc(s.price)}</span><span class="sold">已售 128 件</span><button class="addcircle" data-act="addcart" aria-label="加入购物车">＋</button></div></div></section>`;
if(page==='detail')html=`<div class="hero">${img(s.images[index]||s.images[0],'商品图','gallery-image')}${s.images.length?`<span class="counter">${Math.min(index+1,s.images.length)} / ${s.images.length}</span><button class="prev" data-act="prev" aria-label="上一张">‹</button><button class="next" data-act="next" aria-label="下一张">›</button>`:''}</div><section><div class="price-row"><span class="price">¥${esc(s.price)}</span><span class="sold">已售 128 件</span></div><h2>${esc(s.title)}</h2><p class="mini-meta">${esc(s.unit)} · 按团集中到货</p><p class="intro">${esc(s.intro)}</p></section><section><b>本团自提点</b>${pointCard()}<div class="mini-meta">${esc(s.hours)}</div></section>${s.details.length?`<div class="detail-title">商品详情</div><div class="long-images">${s.details.map((src,i)=>img(src,'商品详情长图'+(i+1))).join('')}</div><div class="detail-end">— 已经到底了 —</div>`:''}`;
if(page==='profile')html=`<div class="profilehead"><span class="avatar">乡</span><div><h2>${logged?'栗子':'当前未登录'}</h2><small>${logged?'欢迎来乡味集':'登录后查看订单与消息提醒'}</small></div></div><section><h3>我的订单</h3><div class="mini-meta">待付款　　待成团　　待领取　　售后</div></section><section><h3>默认自提点</h3>${pointCard()}</section><section><h3>常用服务</h3><div class="service-row" data-page="messages"><span>♧　消息提醒</span><span>${!enabled?'已关闭':statuses.filter(x=>x==='accepted').length+'/5 类已订阅'} ›</span></div><div class="service-row" data-act="orders"><span>▣　取货码</span><span>›</span></div><div class="service-row" data-act="help"><span>♧　帮助与客服</span><span>›</span></div></section>`;
if(page==='messages')html=`<section><h2>消息提醒</h2><p class="mini-meta">重要进度通过微信服务通知送达。</p><div class="service-row"><span>接收本系统提醒</span><button data-act="toggle-reminders">${enabled?'已开启 · 关闭':'已关闭 · 开启'}</button></div><p class="mini-notice">一次订阅对应一次发送机会，发送后可能需要再次订阅。页面展示当前记录，不代表微信永久授权。</p></section><section>${names.map((n,i)=>`<div class="msgitem"><div><b>${n}</b><small>${descriptions[i]}</small><span class="state">${!enabled?'本系统提醒已关闭':({none:'未订阅',accepted:'本次已订阅',used:'需再次订阅',rejected:'未允许'})[statuses[i]]}</span></div><button data-act="subscribe-one" data-i="${i}">${statuses[i]==='accepted'?'查看':'订阅'}</button></div>`).join('')}<button class="primary full" data-act="subscribe">${statuses.every(x=>x==='accepted')?'查看订阅说明':'订阅未开启的提醒'}</button></section><section><div class="service-row" data-act="wechat-settings"><span>微信订阅设置</span><span>查看 / 调整 ›</span></div><p class="hint">关闭系统提醒只停止本系统发送；微信端授权需在微信设置中调整。</p></section>`;
if(page==='pickup')html=`<div class="point-full">${s.photo?img(s.photo,'自提点实景照片'):'<div class="empty">⌖<br>该自提点暂未上传照片</div>'}</div><section><h2>${esc(s.name)}</h2><p class="intro">${esc(s.address)}</p><p class="mini-meta">营业时间：${esc(s.hours)}<br>点位负责人：${esc(s.contact)}</p><div class="point-actions"><button data-act="navigate">导航到这里</button><button data-act="call">联系负责人</button></div></section><section><b>领取提示</b><p class="mini-meta">收到到货通知后，携带取货码到点领取。请核对商品和数量。</p></section>`;
$('#mini').innerHTML=html;$('#mini-footer').innerHTML=page==='detail'?`<div class="buybar"><button class="cart" data-act="addcart">加入购物车${cart?' · '+cart:''}</button><button class="primary" data-act="buy">立即购买</button></div>`:page==='pickup'?'<div class="buybar"><button class="primary" data-act="choose-point">选择此自提点</button></div>':`<nav class="tabbar"><button data-page="home" class="${page==='home'?'active':''}"><b>⌂</b>首页</button><button data-page="detail"><b>▦</b>分类</button><button data-act="cart"><b>♧</b>购物车${cart?'·'+cart:''}</button><button data-page="profile" class="${page==='profile'||page==='messages'?'active':''}"><b>♙</b>我的</button></nav>`}
function go(p){page=p;renderMini();$('#mini').scrollTop=0}
function subscribe(one){if(!logged){modal('登录后订阅','<p>先登录账号，方便关联你的订单与提醒。</p>','<button data-act="close">暂不登录</button><button class="primary" data-act="login">模拟微信登录</button>');return}if(statuses.every(x=>x==='accepted')&&one===undefined){modal('本次消息已订阅','<p>可在「我的 → 消息提醒」查看或关闭本系统提醒。</p><p class="hint">后续发送消耗订阅次数，仍可能需要你再次主动订阅。</p>');return}
enabled=true;const ids=one!==undefined?[one]:statuses.map((x,i)=>x==='accepted'?-1:i).filter(i=>i>=0).slice(0,3);modal('订阅消息 · 原型演示',`<p>选择你关心的提醒，本次最多授权 3 类。</p>${ids.map(i=>`<label class="checkrow"><input type="checkbox" name="subscription" value="${i}" checked><span>${names[i]}<small>${descriptions[i]}</small></span></label>`).join('')}<p class="hint">这是交互模拟；正式版将由微信展示授权窗口。其余提醒需再次点击订阅。</p>`,'<button data-act="deny">模拟不允许</button><button class="primary" data-act="allow">模拟允许</button>')}
function upload(target){uploadTarget=target;const el=$('#file-input');el.multiple=target!=='point';el.value='';el.click()}
document.addEventListener('click',e=>{const el=e.target.closest('button,[data-page],[data-act],[data-admin]');if(!el||el.disabled)return;let a=el.dataset.act,i=Number(el.dataset.i);
if(el.dataset.admin){admin=el.dataset.admin;renderAdmin();return}if(el.dataset.page){go(el.dataset.page);return}
if(a==='close'){close();return}if(a==='back'){go('home');return}if(a==='product-list'){list=true;renderAdmin();return}if(a==='edit-product'){list=false;renderAdmin();return}
if(a==='prev'||a==='next'){index=(index+(a==='next'?1:-1)+s.images.length)%s.images.length||0;renderMini();return}
if(e.target.classList.contains('gallery-image')){modal('商品图片',img(s.images[index],'商品大图','lightbox'));return}
if(a==='remove-image'){s.images.splice(i,1);index=0}else if(a==='left-image'||a==='right-image'){const j=i+(a==='left-image'?-1:1);[s.images[i],s.images[j]]=[s.images[j],s.images[i]];index=0}else if(a==='sample-gallery'){if(s.images.length<5)s.images.push(A+'corn.png');toast('已添加示例图，可换成自己的图片')}else if(a==='sample-detail'){if(s.details.length<10)s.details.push('detail-example.svg')}else if(a==='remove-detail'){s.details.splice(i,1)}else if(a==='left-detail'){[s.details[i-1],s.details[i]]=[s.details[i],s.details[i-1]]}else if(a==='view-detail'){modal('详情长图',img(s.details[i],'详情长图','lightbox'));return}
else if(a==='upload-gallery'){upload('gallery');return}else if(a==='upload-detail'){upload('detail');return}else if(a==='upload-point'){upload('point');return}
else if(a==='save-product'){if(!s.title.trim()||!s.intro.trim()||!s.images.length){toast('请填写名称、商品介绍，并上传至少一张商品图片');return}saved=structuredClone(s);toast('演示保存成功，右侧可查看展示效果');return}else if(a==='cancel-product'){s=structuredClone(saved);index=0;toast('已恢复上次演示保存的内容')}
else if(a==='new-point'||a==='edit-point'){pointEdit=true;pointDraft={name:a==='new-point'?'':s.name,address:a==='new-point'?'':s.address,hours:s.hours,contact:s.contact,photo:a==='new-point'?'':s.photo,isNew:a==='new-point'};renderAdmin();return}else if(a==='cancel-point'){pointEdit=false;pointDraft=null;renderAdmin();return}else if(a==='sample-point'){pointDraft.photo=A+'pickup-point.png';renderAdmin();return}else if(a==='remove-point-photo'){pointDraft.photo='';renderAdmin();return}else if(a==='save-point'){if(!pointDraft.photo||!pointDraft.name.trim()||!pointDraft.address.trim()){toast('请填写名称、地址，并上传自提点照片');return}Object.assign(s,{name:pointDraft.name,address:pointDraft.address,hours:pointDraft.hours,photo:pointDraft.photo});pointEdit=false;pointDraft=null;toast('演示保存成功，自提点照片已同步到预览');go('pickup')}
else if(a==='subscribe'){subscribe();return}else if(a==='subscribe-one'){if(statuses[i]==='accepted'){modal(names[i],'<p>本次已订阅。你可以在消息提醒页面关闭系统提醒，或前往微信设置调整授权。</p>')}else subscribe(i);return}else if(a==='allow'||a==='deny'){const checked=[...document.querySelectorAll('[name="subscription"]:checked')];if(!checked.length){toast('请选择至少一种提醒');return}checked.forEach(x=>statuses[Number(x.value)]=a==='allow'?'accepted':'rejected');close();renderMini();toast(a==='allow'?'本次订阅成功，可在「我的 → 消息提醒」管理':'未允许订阅，首页会保留提示');return}else if(a==='login'){logged=true;close();subscribe();return}
else if(a==='toggle-reminders'){if(enabled){modal('关闭本系统提醒？','<p>关闭后，本系统停止发送这些消息。订单和取货信息仍可在小程序查看。</p><p class="hint">微信授权不会随之撤销，可到微信订阅设置调整。</p>','<button data-act="close">保持开启</button><button class="primary" data-act="confirm-off">关闭提醒</button>')}else{enabled=true;renderMini();toast('已开启系统提醒，请确认需要的订阅授权')}return}else if(a==='confirm-off'){enabled=false;close();renderMini();toast('已关闭本系统提醒');return}else if(a==='wechat-settings'){modal('微信订阅设置','<p>正式版将引导你查看微信订阅消息设置，按微信提供的选项调整授权。</p><p class="hint">此原型不操作你的微信权限，也不将系统关闭动作表述为撤销微信授权。</p>');return}
else if(a==='addcart'){cart++;renderMini();toast('已加入购物车（演示）');return}else if(a==='choose-point'){go('home');toast('已选择此自提点（演示）');return}else if(['buy','cart','navigate','call','orders','help'].includes(a)){toast('这是交互原型，此操作不产生真实业务数据');return}
else if(a==='reset'){s=structuredClone(initial);saved=structuredClone(initial);admin='product';page='detail';list=false;pointEdit=false;index=0;cart=0;statuses=Array(5).fill('none');enabled=true;logged=true;$('#scenario').value='none';toast('已重置演示')}
else if(a==='notes'){modal('这版原型的确认范围',`<div class="notes-grid"><h3>商品内容</h3><p>最多 5 张商品图，第一张作封面；商品介绍最多 300 字；详情长图最多 10 张，底部按原图比例连续展示。</p><h3>交易信息与销量</h3><p>计价单位移入次要设置，保留订单规格。示例累计净销量 = 支付 136 件 − 成功退款 8 件 = 128 件，跨团期统计，不手动编辑。</p><h3>消息提醒</h3><p>首页未订阅时持续提示但不主动弹授权；五类提醒分批授权。我的 → 消息提醒可查看与关闭本系统提醒，微信授权另行管理。</p><h3>自提点照片</h3><p>新增必填一张实景照片；统一用于首页、商品、自提点详情与我的。旧点位没照片显示中性图标。</p><h3>演示方式</h3><p>上传本地图片、调整顺序、输入介绍，在右侧切换页面查看；订阅状态下拉框可测试各种状态。图片及销量均为示例，本页不连接后台。</p></div>`);return}else{return}
renderAdmin();renderMini();});
document.addEventListener('input',e=>{const key=e.target.dataset.field;if(!key)return;if(key.startsWith('point.')){pointDraft[key.slice(6)]=e.target.value;return}s[key]=e.target.value;if(key==='intro')$('#intro-count').textContent=s.intro.length;renderMini()});
$('#scenario').addEventListener('change',e=>{const v=e.target.value;enabled=v!=='off';logged=v!=='guest';statuses=v==='all'?Array(5).fill('accepted'):v==='partial'?['accepted','accepted','none','none','none']:v==='used'?Array(5).fill('used'):Array(5).fill('none');go('home')});
$('#file-input').addEventListener('change',async e=>{const files=[...e.target.files],target=uploadTarget,limit=target==='detail'?10:5,room=target==='gallery'?5-s.images.length:target==='detail'?10-s.details.length:1;if(files.length>room){toast(`最多还能上传 ${room} 张，请重新选择`);return}if(files.some(f=>!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>limit*1024*1024)){toast(`请选择 JPG / PNG / WebP 图片，每张不超过 ${limit} MB`);return}const urls=await Promise.all(files.map(f=>new Promise((resolve,reject)=>{const r=new FileReader;r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(f)}))).catch(()=>null);if(!urls){toast('图片读取失败，请重试');return}if(target==='point'){pointDraft.photo=urls[0]}else{s[target==='gallery'?'images':'details'].push(...urls)}renderAdmin();renderMini();toast('已上传到原型草稿，未发送到服务器')});
document.addEventListener('keydown',e=>{if(e.key==='Escape')close();if((e.key==='Enter'||e.key===' ')&&e.target.matches('[role="button"][data-page]')){e.preventDefault();go(e.target.dataset.page)}});
let touchX=0;$('#mini').addEventListener('touchstart',e=>{touchX=e.touches[0].clientX},{passive:true});$('#mini').addEventListener('touchend',e=>{if(page!=='detail'||!e.target.closest('.hero'))return;const dx=e.changedTouches[0].clientX-touchX;if(Math.abs(dx)>40){index=(index+(dx<0?1:-1)+s.images.length)%s.images.length||0;renderMini()}},{passive:true});
$('#mini').addEventListener('click',e=>{if(e.target.classList.contains('gallery-image'))modal('商品图片',img(s.images[index],'商品大图','lightbox'))});
renderAdmin();renderMini();
