import { Alert, Button, Table, Tag } from 'antd';
import type { CommunityCancellationRequest, CommunityPickupWindow, CommunityQualityCase, FulfillmentException } from '../../api.ts';

type StatusTag = (props: { value: string }) => React.ReactNode;
type Act = (key: string, work: () => Promise<unknown>, success: string) => Promise<void>;
type Can = (...roles: string[]) => boolean;

export const qualityReason: Record<CommunityQualityCase['items'][number]['reason'], string> = { PICKUP_SHORTAGE: '提货短少', PICKUP_DAMAGE: '提货破损', QUALITY_CLAIM: '品质问题' };

/** Role-gated community cancellation, quality and fulfilment queues. */
export function CommunityCaseQueues({ pickupWindows, cancellations, qualityCases, exceptions, loading, can, act, note, dateTime, StatusTag, api }: {
  pickupWindows: CommunityPickupWindow[];
  cancellations: CommunityCancellationRequest[];
  qualityCases: CommunityQualityCase[];
  exceptions: FulfillmentException[];
  loading: boolean;
  can: Can;
  act: Act;
  note(title: string): string | null;
  dateTime: Intl.DateTimeFormat;
  StatusTag: StatusTag;
  api: {
    extendCommunityPickup(orderId: string, deadlineAt: string, note: string): Promise<unknown>;
    disposeCommunityPickup(orderId: string, action: 'REFUND' | 'LOSS', note: string): Promise<unknown>;
    refundExpiredCommunityPickup(orderId: string): Promise<unknown>;
    reviewCommunityCancellation(orderId: string, approved: boolean, note: string): Promise<unknown>;
    refundCommunityCancellation(orderId: string): Promise<unknown>;
    acceptCommunityQualityCase(id: string, note: string): Promise<unknown>;
    decideCommunityQualityCase(id: string, approved: boolean, note: string): Promise<unknown>;
    refundCommunityQualityCase(id: string): Promise<unknown>;
  };
}) {
  return <>
    {can('OPERATOR', 'FINANCE') && <section className="panel panel--spaced"><div className="panel__head"><div><span className="eyebrow">社区团购 · 领取时限</span><h2>领取窗口与逾期处置</h2></div></div><Table<CommunityPickupWindow> rowKey="orderId" loading={loading} dataSource={pickupWindows} pagination={{ pageSize: 8 }} columns={[{ title: '订单', dataIndex: 'orderId', render: (value: string) => <span className="mono">{value}</span> }, { title: '截止时间', dataIndex: 'deadlineAt', render: (value: string) => dateTime.format(new Date(value)) }, { title: '状态', dataIndex: 'status', render: (value: string) => <StatusTag value={value} /> }, { title: '操作', render: (_, record) => <div className="table-actions">{record.status === 'EXPIRED_PENDING' && can('OPERATOR', 'SUPER_ADMIN') && <><Button type="link" onClick={() => { const deadlineAt = window.prompt('延期截止时间（ISO 8601）'); const reason = window.prompt('延期说明'); if (deadlineAt && reason?.trim()) void act(`pickup-extend-${record.orderId}`, () => api.extendCommunityPickup(record.orderId, deadlineAt, reason.trim()), '领取期限已延期'); }}>延期一次</Button><Button type="link" onClick={() => { const reason = note('填写退款原因'); if (reason) void act(`pickup-refund-request-${record.orderId}`, () => api.disposeCommunityPickup(record.orderId, 'REFUND', reason), '已登记逾期退款，待财务执行'); }}>登记退款</Button><Button danger type="link" onClick={() => { const reason = note('填写报损说明'); if (reason) void act(`pickup-loss-${record.orderId}`, () => api.disposeCommunityPickup(record.orderId, 'LOSS', reason), '已完成逾期报损并关闭领取'); }}>报损关闭</Button></>}{record.status === 'REFUND_PENDING' && can('FINANCE', 'SUPER_ADMIN') && <Button type="link" onClick={() => void act(`pickup-refund-execute-${record.orderId}`, () => api.refundExpiredCommunityPickup(record.orderId), '已提交逾期退款，等待支付方最终结果')}>执行退款</Button>}{record.status === 'CLOSED' && <span className="muted">已关闭</span>}</div> }]} /></section>}
    {can('OPERATOR', 'FINANCE', 'CUSTOMER_SERVICE') && <section className="panel panel--spaced"><div className="panel__head"><div><span className="eyebrow">社区团购 · 已付款取消</span><h2>取消申请</h2></div></div><Table<CommunityCancellationRequest> rowKey="id" loading={loading} dataSource={cancellations} pagination={{ pageSize: 8 }} columns={[{ title: '申请时间', dataIndex: 'requestedAt', render: (value: string) => dateTime.format(new Date(value)) }, { title: '订单', dataIndex: 'orderId', render: (value: string) => <span className="mono">{value}</span> }, { title: '用户说明', dataIndex: 'reason' }, { title: '状态', dataIndex: 'status', render: (value: string) => <StatusTag value={value} /> }, { title: '操作', render: (_, record) => <div className="table-actions">{record.status === 'PENDING_REVIEW' && can('OPERATOR', 'SUPER_ADMIN') && <><Button type="link" onClick={() => { const reason = note('填写审核通过说明'); if (reason) void act(`cancel-approve-${record.id}`, () => api.reviewCommunityCancellation(record.orderId, true, reason), '取消申请已批准，待财务退款'); }}>批准</Button><Button danger type="link" onClick={() => { const reason = note('填写驳回原因'); if (reason) void act(`cancel-reject-${record.id}`, () => api.reviewCommunityCancellation(record.orderId, false, reason), '取消申请已驳回'); }}>驳回</Button></>}{record.status === 'APPROVED_WAITING_FINANCE' && can('FINANCE', 'SUPER_ADMIN') && <Button type="link" onClick={() => void act(`cancel-refund-${record.id}`, () => api.refundCommunityCancellation(record.orderId), '已提交原路退款，等待支付方最终结果')}>执行退款</Button>}{['REFUNDING', 'DIRECT_REFUNDING'].includes(record.status) && <span className="muted">退款处理中</span>}{['REFUNDED', 'REJECTED'].includes(record.status) && <span className="muted">已处理</span>}</div> }]} /></section>}
    {can('OPERATOR', 'CUSTOMER_SERVICE', 'FINANCE') && <section className="panel panel--spaced"><div className="panel__head"><div><span className="eyebrow">社区团购 · 分角色处置</span><h2>品质售后案件</h2></div></div><Alert type="info" showIcon message="客服受理，运营决定，财务执行" description="品质退款以支付方最终成功状态为准；处理中或失败案件不会被提前结案。" style={{ marginBottom: 16 }} /><Table<CommunityQualityCase> rowKey="id" loading={loading} dataSource={qualityCases} pagination={{ pageSize: 8 }} scroll={{ x: 880 }} columns={[{ title: '申请时间', dataIndex: 'registeredAt', render: (value: string) => dateTime.format(new Date(value)) }, { title: '订单 / 点位', render: (_, record) => <div><b className="mono">{record.order.orderNo}</b><small className="cell-note">{record.order.pickupPointName}</small></div> }, { title: '商品与数量', render: (_, record) => <div>{record.items.map((item) => <div key={item.salesOrderItemId}><b>{item.skuName}</b><small className="cell-note">申报 {item.disputedQuantity} 件 / 已领取 {item.pickedUpQuantitySnapshot} 件</small></div>)}</div> }, { title: '问题说明', render: (_, record) => <div>{record.items.map((item) => <div key={`${item.salesOrderItemId}-reason`}><b>{qualityReason[item.reason]}</b><small className="cell-note">{item.description}</small></div>)}</div> }, { title: '状态', dataIndex: 'status', render: (value: string) => <StatusTag value={value} /> }, { title: '操作', render: (_, record) => <div className="table-actions">{record.status === 'REGISTERED' && can('CUSTOMER_SERVICE', 'SUPER_ADMIN') && <Button type="link" onClick={() => { const reason = note('填写受理说明'); if (reason) void act(`quality-accept-${record.id}`, () => api.acceptCommunityQualityCase(record.id, reason), '品质售后已受理'); }}>受理</Button>}{record.status === 'ACCEPTED' && can('OPERATOR', 'SUPER_ADMIN') && <><Button type="link" onClick={() => { const reason = note('填写退款审批说明'); if (reason) void act(`quality-approve-${record.id}`, () => api.decideCommunityQualityCase(record.id, true, reason), '已批准品质退款'); }}>批准退款</Button><Button danger type="link" onClick={() => { const reason = note('填写驳回原因'); if (reason) void act(`quality-reject-${record.id}`, () => api.decideCommunityQualityCase(record.id, false, reason), '已驳回品质售后'); }}>驳回</Button></>}{record.status === 'REFUNDING' && can('FINANCE', 'SUPER_ADMIN') && <Button type="link" onClick={() => void act(`quality-refund-${record.id}`, () => api.refundCommunityQualityCase(record.id), '已提交财务退款，等待支付方最终结果')}>执行退款</Button>}{['REJECTED', 'RESOLVED'].includes(record.status) && <Tag>已处理</Tag>}</div> }]} /></section>}
    <section className="panel panel--spaced"><div className="panel__head"><div><span className="eyebrow">社区团购 · 履约异常</span><h2>异常退款追踪</h2></div></div><Table<FulfillmentException> rowKey="id" loading={loading} dataSource={exceptions} pagination={{ pageSize: 8 }} columns={[{ title: '来源', dataIndex: 'sourceStage' }, { title: '异常数量', render: (_, record) => record.items.reduce((sum, item) => sum + item.rejectedQuantity + item.shortQuantity + item.damagedQuantity, 0) }, { title: '状态', dataIndex: 'status', render: (value: string) => <StatusTag value={value} /> }, { title: '处置说明', dataIndex: 'resolutionNote', render: (value: string | null) => value ?? '待运营处置' }]} /></section>
  </>;
}
