const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const handlers = {}, nodes = {};
const node = selector => nodes[selector] ||= { innerHTML: '', textContent: '', style: {}, classList: { toggle() {} }, scrollTo() {} };
const context = { console, setTimeout, clearTimeout, document: { querySelector: node, querySelectorAll: () => [], addEventListener: (event, fn) => handlers[event] = fn } };
vm.createContext(context);
vm.runInContext(fs.readFileSync(__dirname + '/app.js', 'utf8'), context);
const run = script => vm.runInContext(script, context);
const click = data => handlers.click({target: {closest: () => ({dataset: data, tagName: 'BUTTON'})}});
run("state.mode='admin';state.module='finance';state.filter='结果未知';render()");
assert.match(node('#app').innerHTML, /data-detail="1"/);
assert.doesNotMatch(node('#app').innerHTML, /data-detail="0"/);
click({detail: '1'});
assert.match(node('#overlay').innerHTML, /RF-DEMO-002/);
assert.match(node('#overlay').innerHTML, /查询原退款结果/);
assert.doesNotMatch(node('#overlay').innerHTML, /核对退款执行/);
run("state.module='point-workbench';adminDetail(0)");
assert.match(node('#overlay').innerHTML, /arrival-normal/);
assert.doesNotMatch(node('#overlay').innerHTML, /pickup-input/);
node('#arrival-normal').value = '94';node('#arrival-damaged').value = '3';node('#arrival-short').value = '0';
click({action: 'arrival-confirm'});
assert.match(node('#arrival-error').innerHTML, /必须为96/);
run("state.mode='mini';state.page='orders';state.paid=true;state.orderFilter='待付款';render()");
assert.match(node('#app').innerHTML, /这里还没有订单/);
assert.doesNotMatch(node('#app').innerHTML, /待自提<\/span>/);
click({action: 'pay'});
assert.match(node('#overlay').innerHTML, /跳过成团、发车、到货/);
node('#point-area').value='青禾社区（演示）';node('#point-name').value='测试便民店';node('#point-address').value='测试地址12号';node('#point-hours').value='09:00—18:00';node('#point-tip').value='门口领取';
click({map: 'candidates'});
const markup=node('#overlay').innerHTML;
assert.match(markup, /option selected>青禾社区/);
for (const value of ['测试便民店','测试地址12号','09:00—18:00','门口领取']) assert.ok(markup.includes(value));
console.log('PASS: filtered record identity, unknown refund action, arrival form/quantity validation, order status filter, simulated payment disclosure, point form persistence');
